import { Rubik, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LanguageProvider } from "../contexts/LanguageContext";
import Navbar from "./components/navbar";
import Footer from "./components/footer";

const rubik = Rubik({
  variable: "--font-rubik-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${rubik.className} ${geistMono.variable} antialiased`}>
<LanguageProvider>
  <Navbar />
  <main className="pt-16">
    {children}
  </main>
  <Footer />
</LanguageProvider>
      </body>
    </html>
  );
}